site_name: 个人文档

theme: material


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 首页: index.md
  - go:
      - 操作文档: go/搭建环境.md
  - togds:
      - 架构: togds/index.md